name = "my-graphql-app"
main = "./src/index.ts"
compatibility_date = "2025-05-14"

[[kv_namespaces]]
binding = "MY_LIST_KV" # 必须与代码中的 MY_LIST_KV 一致
id = "7435af95c4ba4f07832a944767bfd455" # 从图片中获取

# 例如，定义一个 Durable Object
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# 如果你的 Worker 需要处理静态资产（通常与 Pages 集成时使用）
# [site]
# bucket = "./public" # 你的静态文件所在的目录
# entry-point = "."

# 如果你希望自定义路由
# [[routes]]
# pattern = "/api/*"
# service = "my-graphql-app"